version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: trie_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - trie_data:/data/db

volumes:
  trie_data: {}
