# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/radhikasingh/masters/docs/projects/TrieSearchX

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/radhikasingh/masters/docs/projects/TrieSearchX

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/radhikasingh/masters/docs/projects/TrieSearchX/CMakeFiles /Users/radhikasingh/masters/docs/projects/TrieSearchX//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/radhikasingh/masters/docs/projects/TrieSearchX/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TrieSearchX

# Build rule for target.
TrieSearchX: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TrieSearchX
.PHONY : TrieSearchX

# fast build rule for target.
TrieSearchX/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/build
.PHONY : TrieSearchX/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

scripts/benchmark.o: scripts/benchmark.cpp.o
.PHONY : scripts/benchmark.o

# target to build an object file
scripts/benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/scripts/benchmark.cpp.o
.PHONY : scripts/benchmark.cpp.o

scripts/benchmark.i: scripts/benchmark.cpp.i
.PHONY : scripts/benchmark.i

# target to preprocess a source file
scripts/benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/scripts/benchmark.cpp.i
.PHONY : scripts/benchmark.cpp.i

scripts/benchmark.s: scripts/benchmark.cpp.s
.PHONY : scripts/benchmark.s

# target to generate assembly for a file
scripts/benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/scripts/benchmark.cpp.s
.PHONY : scripts/benchmark.cpp.s

src/MongoConnector.o: src/MongoConnector.cpp.o
.PHONY : src/MongoConnector.o

# target to build an object file
src/MongoConnector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/MongoConnector.cpp.o
.PHONY : src/MongoConnector.cpp.o

src/MongoConnector.i: src/MongoConnector.cpp.i
.PHONY : src/MongoConnector.i

# target to preprocess a source file
src/MongoConnector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/MongoConnector.cpp.i
.PHONY : src/MongoConnector.cpp.i

src/MongoConnector.s: src/MongoConnector.cpp.s
.PHONY : src/MongoConnector.s

# target to generate assembly for a file
src/MongoConnector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/MongoConnector.cpp.s
.PHONY : src/MongoConnector.cpp.s

src/Trie.o: src/Trie.cpp.o
.PHONY : src/Trie.o

# target to build an object file
src/Trie.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/Trie.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/Trie.cpp.o
.PHONY : src/Trie.cpp.o

src/Trie.i: src/Trie.cpp.i
.PHONY : src/Trie.i

# target to preprocess a source file
src/Trie.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/Trie.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/Trie.cpp.i
.PHONY : src/Trie.cpp.i

src/Trie.s: src/Trie.cpp.s
.PHONY : src/Trie.s

# target to generate assembly for a file
src/Trie.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/Trie.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/Trie.cpp.s
.PHONY : src/Trie.cpp.s

src/TrieNode.o: src/TrieNode.cpp.o
.PHONY : src/TrieNode.o

# target to build an object file
src/TrieNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/TrieNode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/TrieNode.cpp.o
.PHONY : src/TrieNode.cpp.o

src/TrieNode.i: src/TrieNode.cpp.i
.PHONY : src/TrieNode.i

# target to preprocess a source file
src/TrieNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/TrieNode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/TrieNode.cpp.i
.PHONY : src/TrieNode.cpp.i

src/TrieNode.s: src/TrieNode.cpp.s
.PHONY : src/TrieNode.s

# target to generate assembly for a file
src/TrieNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/TrieNode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/TrieNode.cpp.s
.PHONY : src/TrieNode.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TrieSearchX.dir/build.make CMakeFiles/TrieSearchX.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TrieSearchX"
	@echo "... benchmark"
	@echo "... scripts/benchmark.o"
	@echo "... scripts/benchmark.i"
	@echo "... scripts/benchmark.s"
	@echo "... src/MongoConnector.o"
	@echo "... src/MongoConnector.i"
	@echo "... src/MongoConnector.s"
	@echo "... src/Trie.o"
	@echo "... src/Trie.i"
	@echo "... src/Trie.s"
	@echo "... src/TrieNode.o"
	@echo "... src/TrieNode.i"
	@echo "... src/TrieNode.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

